const KEY='flip7-score-v2';
const colors=['#ffd21f','#8b5cf6','#f97316','#2f80ed','#ec4899','#22c55e','#06b6d4','#f43f5e'];
let state={players:[],rounds:[],started:false,lastFeedback:null};
const $=id=>document.getElementById(id);
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function load(){try{state={...state,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch(e){}}
function total(p){return state.rounds.reduce((s,r)=>s+(r.scores[p.id]||0),0)}
function ranking(){return [...state.players].map(p=>({...p,total:total(p)})).sort((a,b)=>b.total-a.total||a.name.localeCompare(b.name));}
function screen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.target===id));$('backBtn').style.visibility=id==='participantsScreen'||id==='rankingScreen'?'hidden':'visible';renderAll();}
function initials(n){return n.trim().slice(0,1).toUpperCase()||'?'}
function renderParticipants(){const list=$('participantsList');list.innerHTML='';state.players.forEach((p,i)=>{const row=document.createElement('div');row.className='participant-row';row.innerHTML=`<span class="avatar" style="background:${p.color}">${initials(p.name)}</span><span>${p.name}</span><button aria-label="remover">×</button>`;row.querySelector('button').onclick=()=>{state.players=state.players.filter(x=>x.id!==p.id);state.rounds.forEach(r=>delete r.scores[p.id]);save();renderAll();};list.appendChild(row);});$('startGameBtn').disabled=state.players.length<2;}
function renderRanking(){const r=ranking();$('roundNumber').textContent=state.rounds.length+1;const banner=$('leaderBanner');if(state.lastFeedback){banner.textContent=state.lastFeedback.short;banner.classList.remove('hidden')}else banner.classList.add('hidden');$('rankingList').innerHTML=r.map((p,i)=>`<div class="rank-row ${i===0?'first':''}"><div class="place">${i+1}</div><div class="name">${p.name}${i===0?' <span class="crown">👑</span>':''}</div><div class="score">${p.total}<span class="pts">pts</span></div></div>`).join('')||'<p class="hint center">Adicione participantes para começar.</p>';}
function renderRound(){ $('roundInputNumber').textContent=state.rounds.length+1; const box=$('scoreInputs'); box.innerHTML=''; ranking().forEach((p,i)=>{const row=document.createElement('div');row.className='score-row';row.dataset.id=p.id;row.innerHTML=`<span class="avatar" style="background:${p.color}">${initials(p.name)}</span><span class="pname">${p.name}</span><input inputmode="numeric" pattern="[0-9]*" value="" placeholder="0"><button class="bomb" aria-label="Estourou">💣</button>`;const input=row.querySelector('input'), bomb=row.querySelector('.bomb');bomb.onclick=()=>{bomb.classList.toggle('active'); if(bomb.classList.contains('active')){input.value=0; input.disabled=true}else{input.disabled=false; input.value=''; input.focus();}};box.appendChild(row);});}
function renderHistory(){const table=$('historyTable');if(!state.rounds.length){table.innerHTML='<tbody><tr><td>Nenhuma rodada salva.</td></tr></tbody>';return}const head='<thead><tr><th>Rodada</th>'+state.players.map(p=>`<th>${p.name}</th>`).join('')+'<th>Líder</th></tr></thead>';const body='<tbody>'+[...state.rounds].reverse().map(r=>`<tr><td>${r.number}</td>`+state.players.map(p=>`<td>${r.scores[p.id]??0}</td>`).join('')+`<td>👑 ${r.leaderName||''}</td></tr>`).join('')+'</tbody>';const foot='<tfoot><tr><td>Total</td>'+state.players.map(p=>`<td>${total(p)}</td>`).join('')+`<td>${ranking()[0]?.name||''}</td></tr></tfoot>`;table.innerHTML=head+body+foot;}
function renderFeedback(){const fb=state.lastFeedback;if(!fb)return;$('feedbackTitle').textContent=fb.title;$('feedbackText').textContent=fb.text;$('celebrationIcon').textContent=fb.newLeader?'👑':'🏆';$('feedbackRanking').innerHTML=ranking().map((p,i)=>`<div class="mini-row"><span class="place" style="font-size:28px">${i+1}</span><b>${p.name}</b><span class="m-score">${p.total}</span></div>`).join('')}
function renderAll(){renderParticipants();renderRanking();renderRound();renderHistory();renderFeedback();}
function addParticipant(){const input=$('participantName');const name=input.value.trim();if(!name)return;state.players.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random()),name,color:colors[state.players.length%colors.length]});input.value='';save();renderAll();input.focus();}
function saveRound(){if(!state.players.length)return;const before=ranking()[0]?.id;const scores={};document.querySelectorAll('.score-row').forEach(row=>{const id=row.dataset.id;const bomb=row.querySelector('.bomb').classList.contains('active');const val=parseInt(row.querySelector('input').value||'0',10);scores[id]=bomb?0:Math.max(0,isNaN(val)?0:val);});const tmpRound={number:state.rounds.length+1,scores,leaderName:''};state.rounds.push(tmpRound);const afterRank=ranking();tmpRound.leaderName=afterRank[0]?.name||'';const after=afterRank[0]?.id;const leader=afterRank[0];state.lastFeedback={newLeader:before&&after&&before!==after,title:before&&after&&before!==after?'Nova liderança!':'Líder mantido!',text:before&&after&&before!==after?`${leader.name} assumiu o 1º lugar.`:`${leader?.name||'O líder'} continua em 1º.`,short:before&&after&&before!==after?`👑 ${leader.name} assumiu a liderança`:`👑 ${leader?.name||'Líder'} segue em primeiro`};save();screen('feedbackScreen');}
function undo(){if(!state.rounds.length)return;state.rounds.pop();state.lastFeedback=null;save();renderAll();}
function reset(){if(confirm('Zerar partida e histórico?')){state.rounds=[];state.started=false;state.lastFeedback=null;save();screen('participantsScreen');}}
load();
$('addParticipantBtn').onclick=addParticipant;$('participantName').addEventListener('keydown',e=>{if(e.key==='Enter')addParticipant()});$('startGameBtn').onclick=()=>{state.started=true;save();screen('rankingScreen')};$('goRoundBtn').onclick=()=>screen('roundScreen');$('goHistoryBtn').onclick=()=>screen('historyScreen');$('saveRoundBtn').onclick=saveRound;$('continueBtn').onclick=()=>screen('rankingScreen');$('feedbackHistoryBtn').onclick=()=>screen('historyScreen');$('backRankingBtn').onclick=()=>screen('rankingScreen');$('undoBtn').onclick=undo;$('backBtn').onclick=()=>screen('rankingScreen');$('menuBtn').onclick=()=>$('menuDialog').showModal();$('closeMenuBtn').onclick=()=>$('menuDialog').close();$('resetGameBtn').onclick=()=>{reset();$('menuDialog').close();};document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>screen(b.dataset.target));
renderAll();screen(state.started?'rankingScreen':'participantsScreen');
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
